version: "2"
services:
  rabbit_node_1:
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret_cookie'
    networks:
      - back
    hostname: rabbit_node_1
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    tty: true
    volumes:
      - rabbit1:/var/lib/rabbitmq
      - ./conf/:/etc/rabbitmq/
    command:  bash -c "sleep 10; rabbitmq-server;"
  producer_1:
    networks:
      - back
    hostname: producer_1
    image: "producer-boot"
    ports:
      - "8080:8080"
volumes:
  rabbit1:
    driver: local

networks:
  back:
